export default {
    "alluring": "body",
    "amorphos": "body",
    "aura pulse": "head",
    "aura reader": "head",
    "bioluminescence": "head",
    "blender": "body",
    "blindsense": "head",
    "bloom": "body",
    "breathless": "body",
    "chilled": "body",
    "darkvision": "head",
    "dead silent": "body",
    "drake-touched": "body",
    "dream mist": "head",
    "dream reader": "head",
    "dust up": "body",
    "egg warmer": "body",
    "firestarter": "body",
    "fortune": "head",
    "fountain": "body",
    "freezer": "body",
    "gardener": "head",
    "gather unown": "head",
    "gilled": "body",
    "glow": "body",
    "groundshaper": "body",
    "guster": "body",
    "hazard immunity": "body",
    "hazard tolerance": "body",
    "heart gift": "body",
    "heater": "body",
    "herb growth": "head",
    "honey gather": "body",
    "illusionist": "head",
    "inflatable": "body",
    "invisibility": "head",
    "leaf crafter": "head",
    "legs up": "body",
    "lifesense": "head",
    "line charge": "body",
    "linked evolution": "head",
    "magnetic": "head",
    "mandibles": "head",
    "marsupial": "body",
    "massive weight": "body",
    "materializer": "body",
    "milk collection": "body",
    "mindlock": "head",
    "mountable x": "body",
    "mystical": "head",
    "naturewalk": "body",
    "pack mon": "head",
    "planter": "body",
    "premonition": "head",
    "reach": "body",
    "shapeshifter": "body",
    "shrinkable": "body",
    "soul seer": "head",
    "soul siphon": "head",
    "speech": "head",
    "split evolution": "head",
    "sprouter": "head",
    "stealth": "body",
    "sticky hold": "body",
    "telekinetic": "head",
    "telepath": "head",
    "teleporter": "head",
    "threaded": "body",
    "tracker": "head",
    "tremorsense": "head",
    "trusting": "head",
    "underdog": "head",
    "undergrowth": "body",
    "venom sac": "head",
    "volatile bomb": "head",
    "wallclimber": "body",
    "wavesense": "head",
    "well-built": "body",
    "wielder": "body",
    "wired": "head",
    "x-ray vision": "head",
    "zapper": "head"
}