name: Module Builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install jq
      
      - name: Update module.json
        shell: bash
        run: jq --arg key version --arg value 1.1.2 '(.[$key]) = $value' module.json > tmp.json && mv tmp.json module.json

      - name: Create Zip File
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{github.ref_name}}
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './module.zip, ./module.json'
          tag: ${{github.ref_name}}